name: Gradle Wrapper Command

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"  # Specify the version of JDK you want

      - name: Run Gradle Wrapper
        run: |
          if [ ! -f "gradlew" ]; then
            gradle wrapper
          fi

          # Set permissions for the wrapper script
          chmod +x gradlew
          ./gradlew --version  # You can replace this with any Gradle command.

